import "@/styles/globals.css";

import type { Metadata } from "next";
import { StagewiseToolbar } from "@stagewise/toolbar-next";
import { ReactPlugin } from "@stagewise-plugins/react";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function ChatLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-white">{children}</div>
        <StagewiseToolbar config={{ plugins: [ReactPlugin] }} />
        <Toaster richColors theme="light" />
      </body>
    </html>
  );
}
